// Generated by gencpp from file rm_msgs/Arm_Joint_Speed_Max.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_ARM_JOINT_SPEED_MAX_H
#define RM_MSGS_MESSAGE_ARM_JOINT_SPEED_MAX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rm_msgs
{
template <class ContainerAllocator>
struct Arm_Joint_Speed_Max_
{
  typedef Arm_Joint_Speed_Max_<ContainerAllocator> Type;

  Arm_Joint_Speed_Max_()
    : header()
    , name()
    , max_velocity()  {
    }
  Arm_Joint_Speed_Max_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , max_velocity(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _name_type;
  _name_type name;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _max_velocity_type;
  _max_velocity_type max_velocity;





  typedef boost::shared_ptr< ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> const> ConstPtr;

}; // struct Arm_Joint_Speed_Max_

typedef ::rm_msgs::Arm_Joint_Speed_Max_<std::allocator<void> > Arm_Joint_Speed_Max;

typedef boost::shared_ptr< ::rm_msgs::Arm_Joint_Speed_Max > Arm_Joint_Speed_MaxPtr;
typedef boost::shared_ptr< ::rm_msgs::Arm_Joint_Speed_Max const> Arm_Joint_Speed_MaxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator1> & lhs, const ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name &&
    lhs.max_velocity == rhs.max_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator1> & lhs, const ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96cf1fc11ba4ce2d4aca54cbea5f91a0";
  }

  static const char* value(const ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96cf1fc11ba4ce2dULL;
  static const uint64_t static_value2 = 0x4aca54cbea5f91a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Arm_Joint_Speed_Max";
  }

  static const char* value(const ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string[] name\n"
"float64[] max_velocity\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.max_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Arm_Joint_Speed_Max_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Arm_Joint_Speed_Max_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    if (v.name.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.name[i]);
    }
    if (v.name.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_velocity: ";
    if (v.max_velocity.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.max_velocity.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.max_velocity[i]);
    }
    if (v.max_velocity.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_ARM_JOINT_SPEED_MAX_H
