// Generated by gencpp from file rm_msgs/Cabinet.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_CABINET_H
#define RM_MSGS_MESSAGE_CABINET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace rm_msgs
{
template <class ContainerAllocator>
struct Cabinet_
{
  typedef Cabinet_<ContainerAllocator> Type;

  Cabinet_()
    : header()
    , pose()
    , label(0)
    , angle(0.0)  {
    }
  Cabinet_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)
    , label(0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef int16_t _label_type;
  _label_type label;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::rm_msgs::Cabinet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Cabinet_<ContainerAllocator> const> ConstPtr;

}; // struct Cabinet_

typedef ::rm_msgs::Cabinet_<std::allocator<void> > Cabinet;

typedef boost::shared_ptr< ::rm_msgs::Cabinet > CabinetPtr;
typedef boost::shared_ptr< ::rm_msgs::Cabinet const> CabinetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Cabinet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Cabinet_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Cabinet_<ContainerAllocator1> & lhs, const ::rm_msgs::Cabinet_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose &&
    lhs.label == rhs.label &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Cabinet_<ContainerAllocator1> & lhs, const ::rm_msgs::Cabinet_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Cabinet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Cabinet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Cabinet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Cabinet_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Cabinet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Cabinet_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Cabinet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bea01e89e97f6be121703157e90c7946";
  }

  static const char* value(const ::rm_msgs::Cabinet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbea01e89e97f6be1ULL;
  static const uint64_t static_value2 = 0x21703157e90c7946ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Cabinet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Cabinet";
  }

  static const char* value(const ::rm_msgs::Cabinet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Cabinet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Pose pose     #位姿\n"
"int16 label\n"
"float32 angle   #角度\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rm_msgs::Cabinet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Cabinet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.label);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cabinet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Cabinet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Cabinet_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "label: ";
    Printer<int16_t>::stream(s, indent + "  ", v.label);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_CABINET_H
