// Generated by gencpp from file rm_msgs/Force_Position_State.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_FORCE_POSITION_STATE_H
#define RM_MSGS_MESSAGE_FORCE_POSITION_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Force_Position_State_
{
  typedef Force_Position_State_<ContainerAllocator> Type;

  Force_Position_State_()
    : joint()
    , force(0.0)
    , arm_err(0)
    , dof(0)  {
    }
  Force_Position_State_(const ContainerAllocator& _alloc)
    : joint(_alloc)
    , force(0.0)
    , arm_err(0)
    , dof(0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _joint_type;
  _joint_type joint;

   typedef float _force_type;
  _force_type force;

   typedef uint16_t _arm_err_type;
  _arm_err_type arm_err;

   typedef uint8_t _dof_type;
  _dof_type dof;





  typedef boost::shared_ptr< ::rm_msgs::Force_Position_State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Force_Position_State_<ContainerAllocator> const> ConstPtr;

}; // struct Force_Position_State_

typedef ::rm_msgs::Force_Position_State_<std::allocator<void> > Force_Position_State;

typedef boost::shared_ptr< ::rm_msgs::Force_Position_State > Force_Position_StatePtr;
typedef boost::shared_ptr< ::rm_msgs::Force_Position_State const> Force_Position_StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Force_Position_State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Force_Position_State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Force_Position_State_<ContainerAllocator1> & lhs, const ::rm_msgs::Force_Position_State_<ContainerAllocator2> & rhs)
{
  return lhs.joint == rhs.joint &&
    lhs.force == rhs.force &&
    lhs.arm_err == rhs.arm_err &&
    lhs.dof == rhs.dof;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Force_Position_State_<ContainerAllocator1> & lhs, const ::rm_msgs::Force_Position_State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Force_Position_State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Force_Position_State_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Force_Position_State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73ff0e69e07c4dc10e08479dd9d3ff92";
  }

  static const char* value(const ::rm_msgs::Force_Position_State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73ff0e69e07c4dc1ULL;
  static const uint64_t static_value2 = 0x0e08479dd9d3ff92ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Force_Position_State";
  }

  static const char* value(const ::rm_msgs::Force_Position_State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joint\n"
"float32 force\n"
"uint16 arm_err\n"
"uint8 dof\n"
;
  }

  static const char* value(const ::rm_msgs::Force_Position_State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
      stream.next(m.force);
      stream.next(m.arm_err);
      stream.next(m.dof);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Force_Position_State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Force_Position_State_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "joint: ";
    if (v.joint.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.joint[i]);
    }
    if (v.joint.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "force: ";
    Printer<float>::stream(s, indent + "  ", v.force);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "arm_err: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.arm_err);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dof: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dof);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_FORCE_POSITION_STATE_H
