// Generated by gencpp from file rm_msgs/Manual_Set_Force_Pose.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_MANUAL_SET_FORCE_POSE_H
#define RM_MSGS_MESSAGE_MANUAL_SET_FORCE_POSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Manual_Set_Force_Pose_
{
  typedef Manual_Set_Force_Pose_<ContainerAllocator> Type;

  Manual_Set_Force_Pose_()
    : pose()
    , joint()  {
    }
  Manual_Set_Force_Pose_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , joint(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pose_type;
  _pose_type pose;

   typedef std::vector<int64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int64_t>> _joint_type;
  _joint_type joint;





  typedef boost::shared_ptr< ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> const> ConstPtr;

}; // struct Manual_Set_Force_Pose_

typedef ::rm_msgs::Manual_Set_Force_Pose_<std::allocator<void> > Manual_Set_Force_Pose;

typedef boost::shared_ptr< ::rm_msgs::Manual_Set_Force_Pose > Manual_Set_Force_PosePtr;
typedef boost::shared_ptr< ::rm_msgs::Manual_Set_Force_Pose const> Manual_Set_Force_PoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator1> & lhs, const ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.joint == rhs.joint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator1> & lhs, const ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aeeb8895b8a7ffa8296b1f7ab18fb600";
  }

  static const char* value(const ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaeeb8895b8a7ffa8ULL;
  static const uint64_t static_value2 = 0x296b1f7ab18fb600ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Manual_Set_Force_Pose";
  }

  static const char* value(const ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string pose\n"
"int64[] joint\n"
"\n"
;
  }

  static const char* value(const ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.joint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Manual_Set_Force_Pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Manual_Set_Force_Pose_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joint: ";
    if (v.joint.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int64_t>::stream(s, true ? std::string() : indent + "    ", v.joint[i]);
    }
    if (v.joint.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_MANUAL_SET_FORCE_POSE_H
