// Generated by gencpp from file rm_msgs/MoveJ.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_MOVEJ_H
#define RM_MSGS_MESSAGE_MOVEJ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct MoveJ_
{
  typedef MoveJ_<ContainerAllocator> Type;

  MoveJ_()
    : joint()
    , speed(0.0)
    , trajectory_connect(0)  {
    }
  MoveJ_(const ContainerAllocator& _alloc)
    : joint(_alloc)
    , speed(0.0)
    , trajectory_connect(0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _joint_type;
  _joint_type joint;

   typedef float _speed_type;
  _speed_type speed;

   typedef uint8_t _trajectory_connect_type;
  _trajectory_connect_type trajectory_connect;





  typedef boost::shared_ptr< ::rm_msgs::MoveJ_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::MoveJ_<ContainerAllocator> const> ConstPtr;

}; // struct MoveJ_

typedef ::rm_msgs::MoveJ_<std::allocator<void> > MoveJ;

typedef boost::shared_ptr< ::rm_msgs::MoveJ > MoveJPtr;
typedef boost::shared_ptr< ::rm_msgs::MoveJ const> MoveJConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::MoveJ_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::MoveJ_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::MoveJ_<ContainerAllocator1> & lhs, const ::rm_msgs::MoveJ_<ContainerAllocator2> & rhs)
{
  return lhs.joint == rhs.joint &&
    lhs.speed == rhs.speed &&
    lhs.trajectory_connect == rhs.trajectory_connect;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::MoveJ_<ContainerAllocator1> & lhs, const ::rm_msgs::MoveJ_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::MoveJ_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::MoveJ_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::MoveJ_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::MoveJ_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::MoveJ_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::MoveJ_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::MoveJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c3946ceff2f0db7f69476a4971088db";
  }

  static const char* value(const ::rm_msgs::MoveJ_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c3946ceff2f0db7ULL;
  static const uint64_t static_value2 = 0xf69476a4971088dbULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::MoveJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/MoveJ";
  }

  static const char* value(const ::rm_msgs::MoveJ_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::MoveJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joint\n"
"float32 speed\n"
"uint8 trajectory_connect\n"
;
  }

  static const char* value(const ::rm_msgs::MoveJ_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::MoveJ_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
      stream.next(m.speed);
      stream.next(m.trajectory_connect);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveJ_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::MoveJ_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::MoveJ_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "joint: ";
    if (v.joint.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.joint[i]);
    }
    if (v.joint.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trajectory_connect: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trajectory_connect);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_MOVEJ_H
