# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Force_Position_Move_Joint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Force_Position_Move_Joint(genpy.Message):
  _md5sum = "77bde1aba3500cfee05e409713ffba41"
  _type = "rm_msgs/Force_Position_Move_Joint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32[] joint
uint8 sensor
uint8 mode
uint8 dir
int16 force
uint8 dof"""
  __slots__ = ['joint','sensor','mode','dir','force','dof']
  _slot_types = ['float32[]','uint8','uint8','uint8','int16','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       joint,sensor,mode,dir,force,dof

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Force_Position_Move_Joint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.joint is None:
        self.joint = []
      if self.sensor is None:
        self.sensor = 0
      if self.mode is None:
        self.mode = 0
      if self.dir is None:
        self.dir = 0
      if self.force is None:
        self.force = 0
      if self.dof is None:
        self.dof = 0
    else:
      self.joint = []
      self.sensor = 0
      self.mode = 0
      self.dir = 0
      self.force = 0
      self.dof = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.joint)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.joint))
      _x = self
      buff.write(_get_struct_3BhB().pack(_x.sensor, _x.mode, _x.dir, _x.force, _x.dof))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint = s.unpack(str[start:end])
      _x = self
      start = end
      end += 6
      (_x.sensor, _x.mode, _x.dir, _x.force, _x.dof,) = _get_struct_3BhB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.joint)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.joint.tostring())
      _x = self
      buff.write(_get_struct_3BhB().pack(_x.sensor, _x.mode, _x.dir, _x.force, _x.dof))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 6
      (_x.sensor, _x.mode, _x.dir, _x.force, _x.dof,) = _get_struct_3BhB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3BhB = None
def _get_struct_3BhB():
    global _struct_3BhB
    if _struct_3BhB is None:
        _struct_3BhB = struct.Struct("<3BhB")
    return _struct_3BhB
