# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Tool_IO_State.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Tool_IO_State(genpy.Message):
  _md5sum = "8dedcedb3bfd854b3826d29065f33f9d"
  _type = "rm_msgs/Tool_IO_State"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool[2] Tool_IO_Mode          #数字I/O输入/输出状态  0-输入模式，1-输出模式
bool[2] Tool_IO_State         #数字I/O电平状态      0-低，1-高
"""
  __slots__ = ['Tool_IO_Mode','Tool_IO_State']
  _slot_types = ['bool[2]','bool[2]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Tool_IO_Mode,Tool_IO_State

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Tool_IO_State, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Tool_IO_Mode is None:
        self.Tool_IO_Mode = [False] * 2
      if self.Tool_IO_State is None:
        self.Tool_IO_State = [False] * 2
    else:
      self.Tool_IO_Mode = [False] * 2
      self.Tool_IO_State = [False] * 2

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_2B().pack(*self.Tool_IO_Mode))
      buff.write(_get_struct_2B().pack(*self.Tool_IO_State))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 2
      self.Tool_IO_Mode = _get_struct_2B().unpack(str[start:end])
      self.Tool_IO_Mode = list(map(bool, self.Tool_IO_Mode))
      start = end
      end += 2
      self.Tool_IO_State = _get_struct_2B().unpack(str[start:end])
      self.Tool_IO_State = list(map(bool, self.Tool_IO_State))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.Tool_IO_Mode.tostring())
      buff.write(self.Tool_IO_State.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 2
      self.Tool_IO_Mode = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=2)
      self.Tool_IO_Mode = list(map(bool, self.Tool_IO_Mode))
      start = end
      end += 2
      self.Tool_IO_State = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=2)
      self.Tool_IO_State = list(map(bool, self.Tool_IO_State))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
