# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/write_single_register.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class write_single_register(genpy.Message):
  _md5sum = "967b76240e09e64a48f1fbaa080ed555"
  _type = "rm_msgs/write_single_register"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int8 port
int32 address
int16 data
int16 device
"""
  __slots__ = ['port','address','data','device']
  _slot_types = ['int8','int32','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       port,address,data,device

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(write_single_register, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.port is None:
        self.port = 0
      if self.address is None:
        self.address = 0
      if self.data is None:
        self.data = 0
      if self.device is None:
        self.device = 0
    else:
      self.port = 0
      self.address = 0
      self.data = 0
      self.device = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_bi2h().pack(_x.port, _x.address, _x.data, _x.device))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.port, _x.address, _x.data, _x.device,) = _get_struct_bi2h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_bi2h().pack(_x.port, _x.address, _x.data, _x.device))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.port, _x.address, _x.data, _x.device,) = _get_struct_bi2h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_bi2h = None
def _get_struct_bi2h():
    global _struct_bi2h
    if _struct_bi2h is None:
        _struct_bi2h = struct.Struct("<bi2h")
    return _struct_bi2h
