# Auto-generated by action_planner.py
# -*- coding: utf-8 -*-

from catch import catch_and_place


ACTION_PLAN = [
    {
        "step": 1,
        "action_type": "catch_and_place",
        "source_class": "block1",
        "source_pose": [
            0.1,
            0.2,
            0.3,
            0.0
        ],
        "target_place": [
            0.5,
            0.0,
            0.1
        ],
        "comment": "抓取 block1 放置到第一层位置"
    },
    {
        "step": 2,
        "action_type": "catch_and_place",
        "source_class": "block2",
        "source_pose": [
            0.15,
            0.25,
            0.35,
            0.1
        ],
        "target_place": [
            0.5,
            0.1,
            0.1
        ],
        "comment": "抓取 block2 放置到第二层位置"
    },
    {
        "step": 3,
        "action_type": "catch_and_place",
        "source_class": "block3",
        "source_pose": [
            0.2,
            0.3,
            0.4,
            -0.1
        ],
        "target_place": [
            0.5,
            0.2,
            0.1
        ],
        "comment": "抓取 block3 放置到第三层位置"
    }
]


def get_action_plan():
    """
    返回 action_planner 生成的动作计划。
    """
    return ACTION_PLAN


def run_generated_action_plan(resolve_source_pose, get_arm_orientation_msg):
    """
    参数说明：
    - resolve_source_pose(step): 根据 step 返回 source pose，格式可为:
      [x, y, z, angle] 或 {"pose": [x, y, z, angle]}
    - get_arm_orientation_msg(): 返回 catch_and_place 所需的 arm_orientation_msg

    说明：
    1. 这里先生成一个可调用脚本接口，便于你后面直接在 catch.py 中导入调用。
    2. 当前先复用 catch.py 中的 catch_and_place。
    3. resolve_source_pose / get_arm_orientation_msg 的完整实现，下一步你跑通后再细化。
    """
    for step in ACTION_PLAN:
        source = resolve_source_pose(step)

        if source is None:
            raise RuntimeError(f"Cannot resolve source pose for step: {step}")

        if isinstance(source, dict):
            pose4 = source.get("pose", [])
        else:
            pose4 = source

        if pose4 is None or len(pose4) < 4:
            raise RuntimeError(f"Invalid source pose for step: {step}")

        x, y, z, angle = pose4[0], pose4[1], pose4[2], pose4[3]
        obj_pose_in_base = [x, y, z, 0.0, 0.0, angle]
        arm_orientation_msg = get_arm_orientation_msg()
        target_place_pose = step["target_place"]

        ok = catch_and_place(
            obj_pose_in_base=obj_pose_in_base,
            arm_orientation_msg=arm_orientation_msg,
            target_place_pose=target_place_pose,
            obj_angle=angle,
        )

        if not ok:
            raise RuntimeError(f"catch_and_place failed at step: {step}")

    return True
