from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field
from typing import List
import os
import sys
import json

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# 尽量复用你现有配置；如果没有专门 action_planner_llm，就回退到 task_advisor_llm
try:
    from block_building_agent.config import action_planner_llm as planner_llm
except Exception:
    from block_building_agent.config import task_advisor_llm as planner_llm


class ActionStepItem(BaseModel):
    step: int = Field(description="动作步骤编号，从 1 开始连续递增")
    action_type: str = Field(description="当前动作类型，先固定为 catch_and_place")
    source_class: str = Field(description="待抓取积木类别")
    source_pose: List[float] = Field(
        min_length=4,
        max_length=4,
        description="来源积木位姿，格式 [x, y, z, angle]"
    )
    target_place: List[float] = Field(
        min_length=3,
        max_length=3,
        description="目标放置位置 [x, y, z]"
    )
    comment: str = Field(description="该动作的简短说明")


class ActionPlanOutput(BaseModel):
    action_sequence: List[ActionStepItem] = Field(description="最终动作序列")
    generated_function_name: str = Field(description="生成脚本中的函数名")


def create_action_planner_prompt():
    return ChatPromptTemplate.from_messages([
        ("system", """
你是一个机器人动作规划 Agent。
你的职责是根据：
1. 已验证通过的任务序列
2. YOLO 识别到的真实世界积木信息

生成一个合理的动作序列。

你必须严格遵守以下要求：
1. 只输出 JSON，且必须严格符合 format_instructions。
2. 不要输出解释、注释、推理过程或任何额外文本。
3. 每个 task 对应一个动作步骤。
4. action_type 当前固定为 "catch_and_place"。
5. source_class 必须与任务中的 class_type 一致。
6. source_pose 来自真实世界积木信息，格式固定为 [x, y, z, angle]。
7. target_place 来自任务中的 target_position。
8. 优先选择类别匹配、最先出现的真实积木。
9. generated_function_name 固定输出为 "run_generated_action_plan"。
"""),
        ("human", """
任务序列：
{task_sequence}

真实世界积木信息：
{world_blocks}

请生成动作序列。
{format_instructions}
""")
    ])


def _format_tasks(tasks):
    lines = []
    for i, t in enumerate(tasks):
        lines.append(
            f"[{i}] step={t.get('step')}, "
            f"class_type={t.get('class_type')}, "
            f"target_position={t.get('target_position')}, "
            f"target_posture={t.get('target_posture')}, "
            f"depends_on={t.get('depends_on', [])}"
        )
    return "\n".join(lines) if lines else "[]"


def _format_world_blocks(world_blocks):
    lines = []
    for i, b in enumerate(world_blocks):
        lines.append(
            f"[{i}] object_class={b.get('object_class')}, "
            f"x={b.get('x')}, y={b.get('y')}, z={b.get('z')}, angle={b.get('angle', 0.0)}"
        )
    return "\n".join(lines) if lines else "[]"


def _match_block_for_task(task, world_blocks, used_indices):
    target_class = str(task.get("class_type", ""))
    for idx, blk in enumerate(world_blocks):
        if idx in used_indices:
            continue
        if str(blk.get("object_class", "")) == target_class:
            used_indices.add(idx)
            return blk
    return None


def _fallback_plan(tasks, world_blocks):
    used_indices = set()
    action_sequence = []

    for i, task in enumerate(tasks):
        matched = _match_block_for_task(task, world_blocks, used_indices)
        if matched is None:
            continue

        action_sequence.append({
            "step": i + 1,
            "action_type": "catch_and_place",
            "source_class": str(task.get("class_type", "unknown")),
            "source_pose": [
                float(matched.get("x", 0.0)),
                float(matched.get("y", 0.0)),
                float(matched.get("z", 0.0)),
                float(matched.get("angle", 0.0)),
            ],
            "target_place": list(task.get("target_position", [0.0, 0.0, 0.0])),
            "comment": f"pick class {task.get('class_type')} block from tabletop and place to target"
        })

    return {
        "action_sequence": action_sequence,
        "generated_function_name": "run_generated_action_plan",
    }


def _build_generated_script(action_sequence, function_name):
    plan_json = json.dumps(action_sequence, ensure_ascii=False, indent=4)

    return f'''# Auto-generated by action_planner.py
# -*- coding: utf-8 -*-

from catch import catch_and_place


ACTION_PLAN = {plan_json}


def get_action_plan():
    """
    返回 action_planner 生成的动作计划。
    """
    return ACTION_PLAN


def {function_name}(resolve_source_pose, get_arm_orientation_msg):
    """
    参数说明：
    - resolve_source_pose(step): 根据 step 返回 source pose，格式可为:
      [x, y, z, angle] 或 {{"pose": [x, y, z, angle]}}
    - get_arm_orientation_msg(): 返回 catch_and_place 所需的 arm_orientation_msg

    说明：
    1. 这里先生成一个可调用脚本接口，便于你后面直接在 catch.py 中导入调用。
    2. 当前先复用 catch.py 中的 catch_and_place。
    3. resolve_source_pose / get_arm_orientation_msg 的完整实现，下一步你跑通后再细化。
    """
    for step in ACTION_PLAN:
        source = resolve_source_pose(step)

        if source is None:
            raise RuntimeError(f"Cannot resolve source pose for step: {{step}}")

        if isinstance(source, dict):
            pose4 = source.get("pose", [])
        else:
            pose4 = source

        if pose4 is None or len(pose4) < 4:
            raise RuntimeError(f"Invalid source pose for step: {{step}}")

        x, y, z, angle = pose4[0], pose4[1], pose4[2], pose4[3]
        obj_pose_in_base = [x, y, z, 0.0, 0.0, angle]
        arm_orientation_msg = get_arm_orientation_msg()
        target_place_pose = step["target_place"]

        ok = catch_and_place(
            obj_pose_in_base=obj_pose_in_base,
            arm_orientation_msg=arm_orientation_msg,
            target_place_pose=target_place_pose,
            obj_angle=angle,
        )

        if not ok:
            raise RuntimeError(f"catch_and_place failed at step: {{step}}")

    return True
'''


def action_planner_node(state: dict):
    """
    action_planner:
    接收 final_task_sequence 与 real_blocks_info，
    生成 current_action_sequence/final_action_sequence，
    并落盘生成一个可调用脚本文件。
    """
    tasks = state.get("final_task_sequence") or state.get("current_task_sequence") or []
    world_blocks = state.get("real_blocks_info") or []
    script_output_path = state.get("generated_action_script_path") or "/tmp/generated_action_executor.py"

    if not world_blocks:
        return {
            "action_waiting_for_world": True,
            "action_planner_feedback": "等待接收真实世界的积木信息",
            "current_action_sequence": [],
            "final_action_sequence": None,
            "generated_action_script_path": None,
        }

    prompt = create_action_planner_prompt()
    parser = PydanticOutputParser(pydantic_object=ActionPlanOutput)
    chain = prompt | planner_llm | parser

    try:
        result = chain.invoke({
            "task_sequence": _format_tasks(tasks),
            "world_blocks": _format_world_blocks(world_blocks),
            "format_instructions": parser.get_format_instructions(),
        })

        action_sequence = []
        for item in result.action_sequence:
            if hasattr(item, "model_dump"):
                action_sequence.append(item.model_dump())
            elif hasattr(item, "dict"):
                action_sequence.append(item.dict())
            else:
                action_sequence.append(item)

        function_name = result.generated_function_name or "run_generated_action_plan"
    except Exception as e:
        fallback = _fallback_plan(tasks, world_blocks)
        action_sequence = fallback["action_sequence"]
        function_name = fallback["generated_function_name"]
        feedback = f"action_planner LLM 解析失败，已使用规则回退: {str(e)}"
    else:
        feedback = "action_planner 已完成动作序列规划"

    os.makedirs(os.path.dirname(script_output_path), exist_ok=True)
    script_content = _build_generated_script(action_sequence, function_name)
    with open(script_output_path, "w", encoding="utf-8") as f:
        f.write(script_content)

    return {
        "action_waiting_for_world": False,
        "action_planner_feedback": feedback,
        "current_action_sequence": action_sequence,
        "final_action_sequence": action_sequence,
        "generated_action_script_path": script_output_path,
    }