// Generated by gencpp from file blockkit/ObjectInfo.msg
// DO NOT EDIT!


#ifndef BLOCKKIT_MESSAGE_OBJECTINFO_H
#define BLOCKKIT_MESSAGE_OBJECTINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace blockkit
{
template <class ContainerAllocator>
struct ObjectInfo_
{
  typedef ObjectInfo_<ContainerAllocator> Type;

  ObjectInfo_()
    : object_class()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , angle(0.0)  {
    }
  ObjectInfo_(const ContainerAllocator& _alloc)
    : object_class(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_class_type;
  _object_class_type object_class;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::blockkit::ObjectInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::blockkit::ObjectInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectInfo_

typedef ::blockkit::ObjectInfo_<std::allocator<void> > ObjectInfo;

typedef boost::shared_ptr< ::blockkit::ObjectInfo > ObjectInfoPtr;
typedef boost::shared_ptr< ::blockkit::ObjectInfo const> ObjectInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::blockkit::ObjectInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::blockkit::ObjectInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::blockkit::ObjectInfo_<ContainerAllocator1> & lhs, const ::blockkit::ObjectInfo_<ContainerAllocator2> & rhs)
{
  return lhs.object_class == rhs.object_class &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::blockkit::ObjectInfo_<ContainerAllocator1> & lhs, const ::blockkit::ObjectInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace blockkit

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::blockkit::ObjectInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blockkit::ObjectInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blockkit::ObjectInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blockkit::ObjectInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blockkit::ObjectInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blockkit::ObjectInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::blockkit::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf579c7ee3f17dc8942b83838c4a2ce1";
  }

  static const char* value(const ::blockkit::ObjectInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf579c7ee3f17dc8ULL;
  static const uint64_t static_value2 = 0x942b83838c4a2ce1ULL;
};

template<class ContainerAllocator>
struct DataType< ::blockkit::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "blockkit/ObjectInfo";
  }

  static const char* value(const ::blockkit::ObjectInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::blockkit::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_class  \n"
"float64 x            \n"
"float64 y            \n"
"float64 z \n"
"float64 angle       # object rotation angle in camera frame (radians)\n"
;
  }

  static const char* value(const ::blockkit::ObjectInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::blockkit::ObjectInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_class);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::blockkit::ObjectInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::blockkit::ObjectInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "object_class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_class);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCKKIT_MESSAGE_OBJECTINFO_H
